apiVersion: 1

datasources:
  - name: OpenNMS flow
    type: opennms-flow-datasource
    access: proxy
    url: http://opennms:8980/opennms
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: admin
    isDefault: true
  - name: OpenNMS performance
    type: opennms-performance-datasource
    access: proxy
    url: http://opennms:8980/opennms
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: admin
  - name: OpenNMS entity
    type: opennms-entity-datasource
    access: proxy
    url: http://opennms:8980/opennms
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: admin
  - name: VictoriaLogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victorialogs:9428
