---
version: '3'

volumes:
  data-postgres: {}
  data-opennms: {}
  data-opennms-cfg: {}
  data-grafana: {}

services:
  database:
    image: ${DOCKER_REGISTRY:-docker.io}/timescale/timescaledb:${TIMESCALEDB_VERSION:-latest-pg15}
    environment:
      TZ: ${TIMEZONE:-America/New_York}
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data-postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 30s
      retries: 3

  horizon:
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_ORG:-opennms}/${HORIZON_OCI:-horizon}:${ONMS_VERSION:-latest}
    depends_on:
      - database
    environment:
      TZ: ${TIMEZONE:-America/New_York}
    volumes:
      - data-opennms:/opennms-data
      - data-opennms-cfg:/opt/opennms/etc
      - ./container-fs/opt/opennms/deploy:/opt/opennms/deploy
      - ./container-fs/opt/opennms-overlay:/opt/opennms-overlay
      - ./container-fs/etc/conf.d/confd.toml:/etc/confd/confd.toml
    command: ["-s"]
    ports:
      - "8101:8101/tcp"   # SSH Horizon Karaf shell
      - "8980:8980/tcp"   # HTTP Horizon web ui
      - "10162:1162/udp"  # SNMP trap receiver
      - "11019:11019/tcp" # BMP session listener
    healthcheck:
      test: [ "CMD", "curl", "-f", "-I", "http://localhost:8980/opennms/login.jsp" ]
      interval: 1m
      timeout: 5s
      retries: 3

  grafana:
    image: ${DOCKER_REGISTRY:-docker.io}/grafana/grafana:${GRAFANA_VERSION:-8.5.21}
    depends_on:
      - horizon
    environment:
      TZ: ${TIMEZONE:-America/New_York}
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: https://github.com/OpenNMS/opennms-helm/releases/download/v8.0.4/opennms-helm-app-8.0.4.zip;grafana-piechart-panel;neocat-cal-heatmap-panel
    volumes:
      - data-grafana:/var/lib/grafana
      - ./container-fs/gf-provisioning:/etc/grafana/provisioning/
    ports:
      - "3000:3000/tcp"
