---
version: '3'

volumes:
  data-grafana: {}

services:
  grafana:
    image: ${DOCKER_REGISTRY:-docker.io}/grafana/grafana:${GRAFANA_VERSION:-latest}
    container_name: grafana
    hostname: grafana
    environment:
      TZ: ${TIMEZONE:-America/New_York}
      GF_SECURITY_ADMIN_PASSWORD: mypass
      GF_INSTALL_PLUGINS: opennms-opennms-app,grafana-piechart-panel,neocat-cal-heatmap-panel,briangann-datatable-panel
    volumes:
      - data-grafana:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning/
    ports:
      - "3000:3000/tcp"
