---
postgres:
  host: database
  port: 5432
  user: postgres
  password: postgres

opennms:
  dbname: opennms
  dbuser: opennms
  dbpass: opennms

  timeseries:
    strategy: newts

  rrd:
    storebyforeignsource: true

  cassandra:
    hostname: cassandra-01
    keyspace: newts
    port: 9042
    username: cassandra
    password: cassandra
