---
version: '3'

volumes:
  data-cortex: {}
  data-grafana: {}

services:
  cortex:
    image: ${DOCKER_REGISTRY:-docker.io}/cortexproject/cortex:${CORTEX_VERSION:-v1.13.0}
    container_name: cortex
    volumes:
      - "data-cortex:/tmp/cortex"
      - "./single-process-config.yaml:/etc/single-process-config.yaml"
    command: [ "-config.file=/etc/single-process-config.yaml" ]
    ports:
      - "9009:9009/tcp"
      - "9095:9095/tcp"

  grafana:
    image: ${DOCKER_REGISTRY:-docker.io}/grafana/grafana:${GRAFANA_VERSION:-latest}
    container_name: grafana
    hostname: grafana
    environment:
      TZ: ${TIMEZONE:-America/New_York}
      GF_SECURITY_ADMIN_PASSWORD: mypass
      GF_INSTALL_PLUGIN: opennms-helm-app
    volumes:
      - data-grafana:/var/lib/grafana
      - ./pl-opennms-helm-app.yaml:/etc/grafana/provisioning/plugins/opennms-helm-app.yaml
    ports:
      - "3000:3000/tcp"
