---
version: '3'

volumes:
  data-activemq: {}

services:
  activemq:
    image: ${DOCKER_REGISTRY:-quay.io}/labmonkeys/activemq:${ACTIVEMQ_VERSION:-5.17.4.b1580}
    environment:
      TZ: '${TIMEZONE:-America/New_York}'
    volumes:
      - 'data-activemq:/opt/activemq/data'
      - './container-fs/activemq.xml:/opt/activemq/conf/activemq.xml'
    ports:
      - '61616:61616/tcp'

